#!/usr/bin/env python3
"""
Phase 4: Stochasticity test — 20 cases × 3 runs.
Measures noise in the anti-sycophantic sub-agent prompt.

Reads stochasticity-raw.csv (generated by run_stochasticity.py).
Reports score range, uncertainty agreement, observation count consistency.
"""

import csv, json, os, sys
import statistics
from collections import Counter

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JOB2_DIR = os.path.dirname(SCRIPT_DIR)

LOG = open(os.path.join(SCRIPT_DIR, 'test_stochasticity.log'), 'w')
def log(msg):
    print(msg)
    LOG.write(msg + '\n')

# Load stochasticity results
csv_path = os.path.join(JOB2_DIR, 'stochasticity-raw.csv')
if not os.path.exists(csv_path):
    log("ERROR: stochasticity-raw.csv not found. Run run_stochasticity.py first.")
    sys.exit(1)

rows = []
with open(csv_path) as f:
    reader = csv.DictReader(f)
    for r in reader:
        rows.append(r)

log(f"Loaded {len(rows)} rows from stochasticity-raw.csv")

# Group by case_id
by_case = {}
for r in rows:
    cid = r['case_id']
    if cid not in by_case:
        by_case[cid] = []
    by_case[cid].append(r)

log(f"Cases: {len(by_case)}, runs per case: {[len(v) for v in by_case.values()]}")

# Compute metrics
score_ranges = []
uncertainty_unanimous = 0
any_cannot_assess = 0
cannot_assess_all = 0
obs_a_devs = []
obs_b_devs = []
obs_c_devs = []

for cid, runs in sorted(by_case.items()):
    # Scores
    scores = []
    for r in runs:
        s = r.get('score', '').strip()
        if s and s.lower() not in ('n/a', 'na', ''):
            try:
                scores.append(float(s))
            except ValueError:
                pass

    if len(scores) >= 2:
        score_ranges.append(max(scores) - min(scores))

    # Uncertainty
    uncertainties = [r.get('uncertainty_rating', '').strip().upper() for r in runs]
    if len(set(uncertainties)) == 1:
        uncertainty_unanimous += 1
    if any('CANNOT' in u for u in uncertainties):
        any_cannot_assess += 1
    if all('CANNOT' in u for u in uncertainties):
        cannot_assess_all += 1

    # Observation counts
    for field, devs in [('obs_a_count', obs_a_devs), ('obs_b_count', obs_b_devs), ('obs_c_count', obs_c_devs)]:
        vals = []
        for r in runs:
            v = r.get(field, '').strip()
            if v:
                try:
                    vals.append(float(v))
                except ValueError:
                    pass
        if len(vals) >= 2:
            mean = statistics.mean(vals)
            mad = statistics.mean([abs(v - mean) for v in vals])
            devs.append(mad)

n_cases = len(by_case)

log(f"\n=== STOCHASTICITY RESULTS ===")
log(f"Cases tested: {n_cases}")
log(f"Total rows: {len(rows)}")

if score_ranges:
    log(f"\nScore range (max-min across 3 runs):")
    log(f"  Mean: {statistics.mean(score_ranges):.2f}")
    log(f"  Median: {statistics.median(score_ranges):.2f}")
    log(f"  Max: {max(score_ranges):.2f}")
    log(f"  Min: {min(score_ranges):.2f}")
    log(f"  Cases with score: {len(score_ranges)}/{n_cases}")
else:
    log(f"\nNo cases with numeric scores across multiple runs")

log(f"\nUncertainty rating agreement:")
log(f"  Unanimous (3/3 agree): {uncertainty_unanimous}/{n_cases} ({uncertainty_unanimous/n_cases*100:.0f}%)")
log(f"  At least 1 CANNOT_ASSESS: {any_cannot_assess}/{n_cases} ({any_cannot_assess/n_cases*100:.0f}%)")
log(f"  All 3 CANNOT_ASSESS: {cannot_assess_all}/{n_cases} ({cannot_assess_all/n_cases*100:.0f}%)")

log(f"\nObservation count mean absolute deviation:")
if obs_a_devs:
    log(f"  Observations A (risks added): {statistics.mean(obs_a_devs):.2f}")
if obs_b_devs:
    log(f"  Observations B (risks removed): {statistics.mean(obs_b_devs):.2f}")
if obs_c_devs:
    log(f"  Observations C (severity changed): {statistics.mean(obs_c_devs):.2f}")

# GATES
log(f"\n=== GATES ===")

gate1_pass = True
gate2_pass = True
gate3_pass = True

if score_ranges:
    mean_range = statistics.mean(score_ranges)
    if mean_range > 2.0:
        log(f"GATE 1 FAIL: Mean score range {mean_range:.2f} > 2.0 — prompt too noisy")
        gate1_pass = False
    elif mean_range > 1.0:
        log(f"GATE 1 BORDERLINE: Mean score range {mean_range:.2f} > 1.0 — use 3-run median")
    else:
        log(f"GATE 1 PASS: Mean score range {mean_range:.2f} <= 1.0 — single run OK")
else:
    log(f"GATE 1: Cannot evaluate (no scored cases)")
    gate1_pass = False

uncertainty_agreement = uncertainty_unanimous / n_cases if n_cases > 0 else 0
if uncertainty_agreement < 0.50:
    log(f"GATE 2 FAIL: Uncertainty agreement {uncertainty_agreement:.0%} < 50%")
    gate2_pass = False
elif uncertainty_agreement < 0.70:
    log(f"GATE 2 BORDERLINE: Uncertainty agreement {uncertainty_agreement:.0%} (50-70%)")
else:
    log(f"GATE 2 PASS: Uncertainty agreement {uncertainty_agreement:.0%} >= 70%")

cannot_rate = cannot_assess_all / n_cases if n_cases > 0 else 0
if cannot_rate > 0.80:
    log(f"GATE 3 FAIL: {cannot_rate:.0%} of cases CANNOT_ASSESS — data source lacks signal, STOP")
    gate3_pass = False
else:
    log(f"GATE 3 PASS: CANNOT_ASSESS rate {cannot_rate:.0%} <= 80%")

all_pass = gate1_pass and gate2_pass and gate3_pass
log(f"\nOVERALL: {'ALL GATES PASS' if all_pass else 'GATES FAILED — see above'}")

# Recommend run mode
if gate1_pass and score_ranges:
    mean_range = statistics.mean(score_ranges)
    if mean_range <= 1.0 and uncertainty_agreement >= 0.70:
        log(f"\nRECOMMENDATION: Single run (low noise)")
    else:
        log(f"\nRECOMMENDATION: 3-run median (borderline noise)")

LOG.close()
print(f"\nResults saved to {os.path.join(SCRIPT_DIR, 'test_stochasticity.log')}")
